<?php

/**
 * Statistics filter form base class.
 *
 * @package    read2read
 * @subpackage filter
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseStatisticsFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'period_id'   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Period'), 'add_empty' => true)),
      'category_id' => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Category'), 'add_empty' => true)),
      '1_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '1_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '2_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '2_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '3_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '3_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '4_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '4_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '5_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '5_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '6_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '6_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '7_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '7_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '8_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '8_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '9_buy'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '9_login'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '10_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '10_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '11_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '11_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '12_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '12_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '13_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '13_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '14_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '14_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '15_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '15_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '16_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '16_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '17_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '17_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '18_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '18_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '19_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '19_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '20_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '20_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '21_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '21_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '22_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '22_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '23_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '23_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '24_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '24_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '25_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '25_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '26_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '26_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '27_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '27_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '28_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '28_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '29_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '29_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '30_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '30_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '31_buy'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      '31_login'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'period_id'   => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Period'), 'column' => 'id')),
      'category_id' => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Category'), 'column' => 'id')),
      '1_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '1_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '2_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '2_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '3_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '3_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '4_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '4_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '5_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '5_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '6_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '6_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '7_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '7_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '8_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '8_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '9_buy'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '9_login'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '10_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '10_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '11_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '11_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '12_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '12_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '13_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '13_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '14_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '14_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '15_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '15_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '16_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '16_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '17_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '17_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '18_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '18_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '19_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '19_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '20_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '20_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '21_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '21_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '22_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '22_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '23_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '23_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '24_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '24_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '25_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '25_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '26_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '26_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '27_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '27_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '28_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '28_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '29_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '29_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '30_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '30_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '31_buy'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      '31_login'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('statistics_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Statistics';
  }

  public function getFields()
  {
    return array(
      'id'          => 'Number',
      'period_id'   => 'ForeignKey',
      'category_id' => 'ForeignKey',
      '1_buy'       => 'Number',
      '1_login'     => 'Number',
      '2_buy'       => 'Number',
      '2_login'     => 'Number',
      '3_buy'       => 'Number',
      '3_login'     => 'Number',
      '4_buy'       => 'Number',
      '4_login'     => 'Number',
      '5_buy'       => 'Number',
      '5_login'     => 'Number',
      '6_buy'       => 'Number',
      '6_login'     => 'Number',
      '7_buy'       => 'Number',
      '7_login'     => 'Number',
      '8_buy'       => 'Number',
      '8_login'     => 'Number',
      '9_buy'       => 'Number',
      '9_login'     => 'Number',
      '10_buy'      => 'Number',
      '10_login'    => 'Number',
      '11_buy'      => 'Number',
      '11_login'    => 'Number',
      '12_buy'      => 'Number',
      '12_login'    => 'Number',
      '13_buy'      => 'Number',
      '13_login'    => 'Number',
      '14_buy'      => 'Number',
      '14_login'    => 'Number',
      '15_buy'      => 'Number',
      '15_login'    => 'Number',
      '16_buy'      => 'Number',
      '16_login'    => 'Number',
      '17_buy'      => 'Number',
      '17_login'    => 'Number',
      '18_buy'      => 'Number',
      '18_login'    => 'Number',
      '19_buy'      => 'Number',
      '19_login'    => 'Number',
      '20_buy'      => 'Number',
      '20_login'    => 'Number',
      '21_buy'      => 'Number',
      '21_login'    => 'Number',
      '22_buy'      => 'Number',
      '22_login'    => 'Number',
      '23_buy'      => 'Number',
      '23_login'    => 'Number',
      '24_buy'      => 'Number',
      '24_login'    => 'Number',
      '25_buy'      => 'Number',
      '25_login'    => 'Number',
      '26_buy'      => 'Number',
      '26_login'    => 'Number',
      '27_buy'      => 'Number',
      '27_login'    => 'Number',
      '28_buy'      => 'Number',
      '28_login'    => 'Number',
      '29_buy'      => 'Number',
      '29_login'    => 'Number',
      '30_buy'      => 'Number',
      '30_login'    => 'Number',
      '31_buy'      => 'Number',
      '31_login'    => 'Number',
    );
  }
}
