<?php

/**
 * BaseUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $users
 * @property Doctrine_Collection $permissions
 * @property Doctrine_Collection $Group__Permission
 * @property Doctrine_Collection $User__Group
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()             Returns the current record's "users" collection
 * @method Doctrine_Collection getPermissions()       Returns the current record's "permissions" collection
 * @method Doctrine_Collection getGroupPermission()   Returns the current record's "Group__Permission" collection
 * @method Doctrine_Collection getUserGroup()         Returns the current record's "User__Group" collection
 * @method UserGroup           setName()              Sets the current record's "name" value
 * @method UserGroup           setDescription()       Sets the current record's "description" value
 * @method UserGroup           setUsers()             Sets the current record's "users" collection
 * @method UserGroup           setPermissions()       Sets the current record's "permissions" collection
 * @method UserGroup           setGroupPermission()   Sets the current record's "Group__Permission" collection
 * @method UserGroup           setUserGroup()         Sets the current record's "User__Group" collection
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as users', array(
             'refClass' => 'User__Group',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('UserPermission as permissions', array(
             'refClass' => 'Group__Permission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Group__Permission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('User__Group', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}