<?php

/**
 * BaseUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Group__Permission
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getPermissions()       Returns the current record's "Permissions" collection
 * @method Doctrine_Collection getGroupPermission()   Returns the current record's "Group__Permission" collection
 * @method UserPermission      setName()              Sets the current record's "name" value
 * @method UserPermission      setDescription()       Sets the current record's "description" value
 * @method UserPermission      setPermissions()       Sets the current record's "Permissions" collection
 * @method UserPermission      setGroupPermission()   Sets the current record's "Group__Permission" collection
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserGroup as Permissions', array(
             'refClass' => 'Group__Permission',
             'local' => 'permission_id',
             'foreign' => 'group_id'));

        $this->hasMany('Group__Permission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}