<?php

/**
 * BaseVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_period
 * @property integer $id_user
 * @property decimal $price
 * @property integer $position
 * @property decimal $weight
 * @property integer $joins
 * @property Period $Period
 * @property User $User
 * @property Doctrine_Collection $Voters
 * 
 * @method integer             getIdPeriod()  Returns the current record's "id_period" value
 * @method integer             getIdUser()    Returns the current record's "id_user" value
 * @method decimal             getPrice()     Returns the current record's "price" value
 * @method integer             getPosition()  Returns the current record's "position" value
 * @method decimal             getWeight()    Returns the current record's "weight" value
 * @method integer             getJoins()     Returns the current record's "joins" value
 * @method Period              getPeriod()    Returns the current record's "Period" value
 * @method User                getUser()      Returns the current record's "User" value
 * @method Doctrine_Collection getVoters()    Returns the current record's "Voters" collection
 * @method Vote                setIdPeriod()  Sets the current record's "id_period" value
 * @method Vote                setIdUser()    Sets the current record's "id_user" value
 * @method Vote                setPrice()     Sets the current record's "price" value
 * @method Vote                setPosition()  Sets the current record's "position" value
 * @method Vote                setWeight()    Sets the current record's "weight" value
 * @method Vote                setJoins()     Sets the current record's "joins" value
 * @method Vote                setPeriod()    Sets the current record's "Period" value
 * @method Vote                setUser()      Sets the current record's "User" value
 * @method Vote                setVoters()    Sets the current record's "Voters" collection
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote');
        $this->hasColumn('id_period', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_user', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             ));
        $this->hasColumn('position', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('weight', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             ));
        $this->hasColumn('joins', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Period', array(
             'local' => 'id_period',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'id_user',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $this->hasMany('Voters', array(
             'local' => 'id',
             'foreign' => 'id_vote'));
    }
}