<?php

/**
 * BaseParagraph
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_content
 * @property clob $paragraph_ru
 * @property clob $paragraph_en
 * @property integer $ordered
 * @property Content $Content
 * @property Doctrine_Collection $Comment
 * 
 * @method integer             getIdContent()    Returns the current record's "id_content" value
 * @method clob                getParagraphRu()  Returns the current record's "paragraph_ru" value
 * @method clob                getParagraphEn()  Returns the current record's "paragraph_en" value
 * @method integer             getOrdered()      Returns the current record's "ordered" value
 * @method Content             getContent()      Returns the current record's "Content" value
 * @method Doctrine_Collection getComment()      Returns the current record's "Comment" collection
 * @method Paragraph           setIdContent()    Sets the current record's "id_content" value
 * @method Paragraph           setParagraphRu()  Sets the current record's "paragraph_ru" value
 * @method Paragraph           setParagraphEn()  Sets the current record's "paragraph_en" value
 * @method Paragraph           setOrdered()      Sets the current record's "ordered" value
 * @method Paragraph           setContent()      Sets the current record's "Content" value
 * @method Paragraph           setComment()      Sets the current record's "Comment" collection
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParagraph extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paragraph');
        $this->hasColumn('id_content', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('paragraph_ru', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('paragraph_en', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('ordered', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'id_content',
             'foreign' => 'id'));

        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'id_paragraph'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}