<?php

/**
 * BaseVoters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_vote
 * @property integer $id_user
 * @property Vote $Vote
 * @property User $User
 * 
 * @method integer getIdVote()  Returns the current record's "id_vote" value
 * @method integer getIdUser()  Returns the current record's "id_user" value
 * @method Vote    getVote()    Returns the current record's "Vote" value
 * @method User    getUser()    Returns the current record's "User" value
 * @method Voters  setIdVote()  Sets the current record's "id_vote" value
 * @method Voters  setIdUser()  Sets the current record's "id_user" value
 * @method Voters  setVote()    Sets the current record's "Vote" value
 * @method Voters  setUser()    Sets the current record's "User" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('voters');
        $this->hasColumn('id_vote', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_user', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vote', array(
             'local' => 'id_vote',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'id_user',
             'foreign' => 'id'));
    }
}