<?php

/**
 * BaseStatistics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $period_id
 * @property integer $category_id
 * @property integer $1_buy
 * @property integer $1_login
 * @property integer $2_buy
 * @property integer $2_login
 * @property integer $3_buy
 * @property integer $3_login
 * @property integer $4_buy
 * @property integer $4_login
 * @property integer $5_buy
 * @property integer $5_login
 * @property integer $6_buy
 * @property integer $6_login
 * @property integer $7_buy
 * @property integer $7_login
 * @property integer $8_buy
 * @property integer $8_login
 * @property integer $9_buy
 * @property integer $9_login
 * @property integer $10_buy
 * @property integer $10_login
 * @property integer $11_buy
 * @property integer $11_login
 * @property integer $12_buy
 * @property integer $12_login
 * @property integer $13_buy
 * @property integer $13_login
 * @property integer $14_buy
 * @property integer $14_login
 * @property integer $15_buy
 * @property integer $15_login
 * @property integer $16_buy
 * @property integer $16_login
 * @property integer $17_buy
 * @property integer $17_login
 * @property integer $18_buy
 * @property integer $18_login
 * @property integer $19_buy
 * @property integer $19_login
 * @property integer $20_buy
 * @property integer $20_login
 * @property integer $21_buy
 * @property integer $21_login
 * @property integer $22_buy
 * @property integer $22_login
 * @property integer $23_buy
 * @property integer $23_login
 * @property integer $24_buy
 * @property integer $24_login
 * @property integer $25_buy
 * @property integer $25_login
 * @property integer $26_buy
 * @property integer $26_login
 * @property integer $27_buy
 * @property integer $27_login
 * @property integer $28_buy
 * @property integer $28_login
 * @property integer $29_buy
 * @property integer $29_login
 * @property integer $30_buy
 * @property integer $30_login
 * @property integer $31_buy
 * @property integer $31_login
 * @property Period $Period
 * @property Category $Category
 * 
 * @method integer    getPeriodId()    Returns the current record's "period_id" value
 * @method integer    getCategoryId()  Returns the current record's "category_id" value
 * @method integer    get1Buy()        Returns the current record's "1_buy" value
 * @method integer    get1Login()      Returns the current record's "1_login" value
 * @method integer    get2Buy()        Returns the current record's "2_buy" value
 * @method integer    get2Login()      Returns the current record's "2_login" value
 * @method integer    get3Buy()        Returns the current record's "3_buy" value
 * @method integer    get3Login()      Returns the current record's "3_login" value
 * @method integer    get4Buy()        Returns the current record's "4_buy" value
 * @method integer    get4Login()      Returns the current record's "4_login" value
 * @method integer    get5Buy()        Returns the current record's "5_buy" value
 * @method integer    get5Login()      Returns the current record's "5_login" value
 * @method integer    get6Buy()        Returns the current record's "6_buy" value
 * @method integer    get6Login()      Returns the current record's "6_login" value
 * @method integer    get7Buy()        Returns the current record's "7_buy" value
 * @method integer    get7Login()      Returns the current record's "7_login" value
 * @method integer    get8Buy()        Returns the current record's "8_buy" value
 * @method integer    get8Login()      Returns the current record's "8_login" value
 * @method integer    get9Buy()        Returns the current record's "9_buy" value
 * @method integer    get9Login()      Returns the current record's "9_login" value
 * @method integer    get10Buy()       Returns the current record's "10_buy" value
 * @method integer    get10Login()     Returns the current record's "10_login" value
 * @method integer    get11Buy()       Returns the current record's "11_buy" value
 * @method integer    get11Login()     Returns the current record's "11_login" value
 * @method integer    get12Buy()       Returns the current record's "12_buy" value
 * @method integer    get12Login()     Returns the current record's "12_login" value
 * @method integer    get13Buy()       Returns the current record's "13_buy" value
 * @method integer    get13Login()     Returns the current record's "13_login" value
 * @method integer    get14Buy()       Returns the current record's "14_buy" value
 * @method integer    get14Login()     Returns the current record's "14_login" value
 * @method integer    get15Buy()       Returns the current record's "15_buy" value
 * @method integer    get15Login()     Returns the current record's "15_login" value
 * @method integer    get16Buy()       Returns the current record's "16_buy" value
 * @method integer    get16Login()     Returns the current record's "16_login" value
 * @method integer    get17Buy()       Returns the current record's "17_buy" value
 * @method integer    get17Login()     Returns the current record's "17_login" value
 * @method integer    get18Buy()       Returns the current record's "18_buy" value
 * @method integer    get18Login()     Returns the current record's "18_login" value
 * @method integer    get19Buy()       Returns the current record's "19_buy" value
 * @method integer    get19Login()     Returns the current record's "19_login" value
 * @method integer    get20Buy()       Returns the current record's "20_buy" value
 * @method integer    get20Login()     Returns the current record's "20_login" value
 * @method integer    get21Buy()       Returns the current record's "21_buy" value
 * @method integer    get21Login()     Returns the current record's "21_login" value
 * @method integer    get22Buy()       Returns the current record's "22_buy" value
 * @method integer    get22Login()     Returns the current record's "22_login" value
 * @method integer    get23Buy()       Returns the current record's "23_buy" value
 * @method integer    get23Login()     Returns the current record's "23_login" value
 * @method integer    get24Buy()       Returns the current record's "24_buy" value
 * @method integer    get24Login()     Returns the current record's "24_login" value
 * @method integer    get25Buy()       Returns the current record's "25_buy" value
 * @method integer    get25Login()     Returns the current record's "25_login" value
 * @method integer    get26Buy()       Returns the current record's "26_buy" value
 * @method integer    get26Login()     Returns the current record's "26_login" value
 * @method integer    get27Buy()       Returns the current record's "27_buy" value
 * @method integer    get27Login()     Returns the current record's "27_login" value
 * @method integer    get28Buy()       Returns the current record's "28_buy" value
 * @method integer    get28Login()     Returns the current record's "28_login" value
 * @method integer    get29Buy()       Returns the current record's "29_buy" value
 * @method integer    get29Login()     Returns the current record's "29_login" value
 * @method integer    get30Buy()       Returns the current record's "30_buy" value
 * @method integer    get30Login()     Returns the current record's "30_login" value
 * @method integer    get31Buy()       Returns the current record's "31_buy" value
 * @method integer    get31Login()     Returns the current record's "31_login" value
 * @method Period     getPeriod()      Returns the current record's "Period" value
 * @method Category   getCategory()    Returns the current record's "Category" value
 * @method Statistics setPeriodId()    Sets the current record's "period_id" value
 * @method Statistics setCategoryId()  Sets the current record's "category_id" value
 * @method Statistics set1Buy()        Sets the current record's "1_buy" value
 * @method Statistics set1Login()      Sets the current record's "1_login" value
 * @method Statistics set2Buy()        Sets the current record's "2_buy" value
 * @method Statistics set2Login()      Sets the current record's "2_login" value
 * @method Statistics set3Buy()        Sets the current record's "3_buy" value
 * @method Statistics set3Login()      Sets the current record's "3_login" value
 * @method Statistics set4Buy()        Sets the current record's "4_buy" value
 * @method Statistics set4Login()      Sets the current record's "4_login" value
 * @method Statistics set5Buy()        Sets the current record's "5_buy" value
 * @method Statistics set5Login()      Sets the current record's "5_login" value
 * @method Statistics set6Buy()        Sets the current record's "6_buy" value
 * @method Statistics set6Login()      Sets the current record's "6_login" value
 * @method Statistics set7Buy()        Sets the current record's "7_buy" value
 * @method Statistics set7Login()      Sets the current record's "7_login" value
 * @method Statistics set8Buy()        Sets the current record's "8_buy" value
 * @method Statistics set8Login()      Sets the current record's "8_login" value
 * @method Statistics set9Buy()        Sets the current record's "9_buy" value
 * @method Statistics set9Login()      Sets the current record's "9_login" value
 * @method Statistics set10Buy()       Sets the current record's "10_buy" value
 * @method Statistics set10Login()     Sets the current record's "10_login" value
 * @method Statistics set11Buy()       Sets the current record's "11_buy" value
 * @method Statistics set11Login()     Sets the current record's "11_login" value
 * @method Statistics set12Buy()       Sets the current record's "12_buy" value
 * @method Statistics set12Login()     Sets the current record's "12_login" value
 * @method Statistics set13Buy()       Sets the current record's "13_buy" value
 * @method Statistics set13Login()     Sets the current record's "13_login" value
 * @method Statistics set14Buy()       Sets the current record's "14_buy" value
 * @method Statistics set14Login()     Sets the current record's "14_login" value
 * @method Statistics set15Buy()       Sets the current record's "15_buy" value
 * @method Statistics set15Login()     Sets the current record's "15_login" value
 * @method Statistics set16Buy()       Sets the current record's "16_buy" value
 * @method Statistics set16Login()     Sets the current record's "16_login" value
 * @method Statistics set17Buy()       Sets the current record's "17_buy" value
 * @method Statistics set17Login()     Sets the current record's "17_login" value
 * @method Statistics set18Buy()       Sets the current record's "18_buy" value
 * @method Statistics set18Login()     Sets the current record's "18_login" value
 * @method Statistics set19Buy()       Sets the current record's "19_buy" value
 * @method Statistics set19Login()     Sets the current record's "19_login" value
 * @method Statistics set20Buy()       Sets the current record's "20_buy" value
 * @method Statistics set20Login()     Sets the current record's "20_login" value
 * @method Statistics set21Buy()       Sets the current record's "21_buy" value
 * @method Statistics set21Login()     Sets the current record's "21_login" value
 * @method Statistics set22Buy()       Sets the current record's "22_buy" value
 * @method Statistics set22Login()     Sets the current record's "22_login" value
 * @method Statistics set23Buy()       Sets the current record's "23_buy" value
 * @method Statistics set23Login()     Sets the current record's "23_login" value
 * @method Statistics set24Buy()       Sets the current record's "24_buy" value
 * @method Statistics set24Login()     Sets the current record's "24_login" value
 * @method Statistics set25Buy()       Sets the current record's "25_buy" value
 * @method Statistics set25Login()     Sets the current record's "25_login" value
 * @method Statistics set26Buy()       Sets the current record's "26_buy" value
 * @method Statistics set26Login()     Sets the current record's "26_login" value
 * @method Statistics set27Buy()       Sets the current record's "27_buy" value
 * @method Statistics set27Login()     Sets the current record's "27_login" value
 * @method Statistics set28Buy()       Sets the current record's "28_buy" value
 * @method Statistics set28Login()     Sets the current record's "28_login" value
 * @method Statistics set29Buy()       Sets the current record's "29_buy" value
 * @method Statistics set29Login()     Sets the current record's "29_login" value
 * @method Statistics set30Buy()       Sets the current record's "30_buy" value
 * @method Statistics set30Login()     Sets the current record's "30_login" value
 * @method Statistics set31Buy()       Sets the current record's "31_buy" value
 * @method Statistics set31Login()     Sets the current record's "31_login" value
 * @method Statistics setPeriod()      Sets the current record's "Period" value
 * @method Statistics setCategory()    Sets the current record's "Category" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatistics extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('statistics');
        $this->hasColumn('period_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('1_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('1_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('2_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('2_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('3_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('3_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('4_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('4_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('5_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('5_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('6_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('6_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('7_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('7_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('8_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('8_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('9_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('9_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('10_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('10_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('11_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('11_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('12_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('12_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('13_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('13_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('14_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('14_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('15_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('15_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('16_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('16_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('17_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('17_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('18_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('18_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('19_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('19_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('20_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('20_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('21_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('21_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('22_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('22_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('23_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('23_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('24_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('24_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('25_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('25_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('26_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('26_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('27_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('27_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('28_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('28_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('29_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('29_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('30_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('30_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('31_buy', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('31_login', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Period', array(
             'local' => 'period_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}