<?php

/**
 * BaseContentPurchase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property integer $id_category
 * @property integer $id_content
 * @property User $User
 * @property Category $Category
 * @property Content $Content
 * 
 * @method integer         getIdUser()      Returns the current record's "id_user" value
 * @method integer         getIdCategory()  Returns the current record's "id_category" value
 * @method integer         getIdContent()   Returns the current record's "id_content" value
 * @method User            getUser()        Returns the current record's "User" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method Content         getContent()     Returns the current record's "Content" value
 * @method ContentPurchase setIdUser()      Sets the current record's "id_user" value
 * @method ContentPurchase setIdCategory()  Sets the current record's "id_category" value
 * @method ContentPurchase setIdContent()   Sets the current record's "id_content" value
 * @method ContentPurchase setUser()        Sets the current record's "User" value
 * @method ContentPurchase setCategory()    Sets the current record's "Category" value
 * @method ContentPurchase setContent()     Sets the current record's "Content" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentPurchase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_purchase');
        $this->hasColumn('id_user', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_category', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_content', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'id_category',
             'foreign' => 'id'));

        $this->hasOne('Content', array(
             'local' => 'id_content',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}