<?php

/**
 * BaseStatisticsCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $user_id
 * @property date $visit_date
 * 
 * @method integer            getCategoryId()  Returns the current record's "category_id" value
 * @method integer            getUserId()      Returns the current record's "user_id" value
 * @method date               getVisitDate()   Returns the current record's "visit_date" value
 * @method StatisticsCategory setCategoryId()  Sets the current record's "category_id" value
 * @method StatisticsCategory setUserId()      Sets the current record's "user_id" value
 * @method StatisticsCategory setVisitDate()   Sets the current record's "visit_date" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatisticsCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('statistics_category');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('visit_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));


        $this->index('full', array(
             'fields' => 
             array(
              0 => 'visit_date',
              1 => 'category_id',
              2 => 'user_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}