<?php

/**
 * BaseGroup__Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $permission_id
 * @property UserGroup $Group
 * @property UserPermission $Permission
 * 
 * @method integer           getGroupId()       Returns the current record's "group_id" value
 * @method integer           getPermissionId()  Returns the current record's "permission_id" value
 * @method UserGroup         getGroup()         Returns the current record's "Group" value
 * @method UserPermission    getPermission()    Returns the current record's "Permission" value
 * @method Group__Permission setGroupId()       Sets the current record's "group_id" value
 * @method Group__Permission setPermissionId()  Sets the current record's "permission_id" value
 * @method Group__Permission setGroup()         Sets the current record's "Group" value
 * @method Group__Permission setPermission()    Sets the current record's "Permission" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup__Permission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group__user_permission');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UserPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}