<?php

/**
 * BaseContentRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $user_id
 * @property integer $period_id
 * @property integer $content_rating
 * @property integer $translate_rating
 * @property Period $Period
 * @property User $User
 * @property Content $Content
 * 
 * @method integer       getContentId()        Returns the current record's "content_id" value
 * @method integer       getUserId()           Returns the current record's "user_id" value
 * @method integer       getPeriodId()         Returns the current record's "period_id" value
 * @method integer       getContentRating()    Returns the current record's "content_rating" value
 * @method integer       getTranslateRating()  Returns the current record's "translate_rating" value
 * @method Period        getPeriod()           Returns the current record's "Period" value
 * @method User          getUser()             Returns the current record's "User" value
 * @method Content       getContent()          Returns the current record's "Content" value
 * @method ContentRating setContentId()        Sets the current record's "content_id" value
 * @method ContentRating setUserId()           Sets the current record's "user_id" value
 * @method ContentRating setPeriodId()         Sets the current record's "period_id" value
 * @method ContentRating setContentRating()    Sets the current record's "content_rating" value
 * @method ContentRating setTranslateRating()  Sets the current record's "translate_rating" value
 * @method ContentRating setPeriod()           Sets the current record's "Period" value
 * @method ContentRating setUser()             Sets the current record's "User" value
 * @method ContentRating setContent()          Sets the current record's "Content" value
 * 
 * @package    read2read
 * @subpackage model
 * @author     aSoft4Web Team <info@asoft4web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_rating');
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('period_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content_rating', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('translate_rating', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Period', array(
             'local' => 'period_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));
    }
}