<?php

/**
 * BalanceUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BalanceUserTable extends Doctrine_Table
{
    /**
     * Enter description here...
     *
     * @param int $user_id
     * @param int $period_id
     * @return BalanceUser
     */
    public static function getByUserIdAndPeriodId($user_id, $period_id = 0)
    {
        if ($period_id == 0) {
            $period_id = Period::getCurrentPeriod()->getId();
        }
        $q = Doctrine_Query::create()
            ->from('BalanceUser bu')
            ->where('bu.id_user=?', $user_id)
            ->andWhere('bu.id_period=?', $period_id)
            ->limit(1);
        $balance = $q->fetchOne();
        if (false === $balance) {
            BalanceUser::setInitialRecord($user_id, $period_id);
            $balance = self::getByUserIdAndPeriodId($user_id, $period_id);
            //throw new sfException('Cannot get Balance for User: '.$user_id.' period: '.$period_id.'. Error in DB data');
        }

        return $balance;
    }


    /**
     * Returns an instance of this class.
     *
     * @return object BalanceUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BalanceUser');
    }

    public static function setPaid($pay_id, $amount)
    {
        $sum = 0;
        $q = Doctrine_Query::create()
            ->select('bu.*')
            ->from('BalanceUser bu')
            ->where('bu.was_paid_id = ?', $pay_id)
            ->andWhere('bu.was_paid = 0')
            ->execute();

        foreach ($q as $bu) {
            $bu->setWasPaid(true);
            $bu->setWasPaidAmount($amount);
            $bu->save();
            $sum += $bu->getPayable();
        }

        return $sum;
    }
}