<?php

/**
 * BalanceUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BalanceUser extends BaseBalanceUser
{

    public static function setInitialRecord($user_id, $period_id)
    {
        $userBalance = new BalanceUser;

        $userBalance->setIdUser($user_id);
        $userBalance->setIdPeriod($period_id);
        $userBalance->setSellPurchaseCnt(0);
        $userBalance->setAmount(0);

        $userBalance->save();

    }

}
