<?php

/**
 * BalanceSystemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BalanceSystemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BalanceSystemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BalanceSystem');
    }
}