<?php

/**
 * BalanceSystem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BalanceSystem extends BaseBalanceSystem
{

    public function getDepositPUsers()
    {
        return $this->getDepositStandart() + $this->getDepositSuper() + $this->getDepositExpert();
    }

    public function getChargesPUsers()
    {
        return $this->getChargesStandart() + $this->getChargesSuper() + $this->getChargesExpert();
    }

    public function getInBalancePUsers()
    {
        return $this->getInBalanceStandart() + $this->getInBalanceSuper() + $this->getInBalanceExpert();
    }

    public function getSalesPUsers()
    {
        return $this->getSalesStandart() + $this->getSalesSuper() + $this->getSalesExpert();
    }

    public function getToPayPUsers()
    {
        return $this->getToPayStandart() + $this->getToPaySuper() + $this->getToPayExpert();
    }

    public function getR2rPUsers()
    {
        return $this->getR2rStandart() + $this->getR2rSuper() + $this->getR2rExpert();
    }

    public static function getCurrentBalanceInstance()
    {
        $sysBalance = BalanceSystemTable::getInstance()->findOneByIdPeriod(Period::getCurrentPeriod()->getId());
        if (!$sysBalance) {
            $sysBalance = new BalanceSystem();
            $sysBalance->setPeriod(Period::getCurrentPeriod());
            $sysBalance->countInBalance();
            $sysBalance->save();
        }

        return $sysBalance;
    }

    public function countInBalance()
    {
        if ($this->getInBalancePUsers() + $this->getInBalanceUser() > 0) {
            // похоже уже считали входной баланс, сваливаем
            return;
        }

        $this->setInBalanceUser((float)UserTable::getUsersBalance('none'));
        $this->setInBalanceStandart((float)UserTable::getUsersBalance('standart'));
        $this->setInBalanceExpert((float)UserTable::getUsersBalance('expert'));
        $this->setInBalanceSuper((float)UserTable::getUsersBalance('super'));
    }

}
