<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
  
    /**
     * Returns a Category main page list
     *
     * @return object Doctrine_Collection
     */
    public function getMainPageList()
    {
      $q = $this->createQuery('c')
            ->orderBy('ordered');
      return $q->execute();
    }
    
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
}