<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{

  public function postInsert($event)
  {
    $oStatistics = new Statistics();
    $oStatistics->setCategoryId($this->getId());
    try
    {
        $iPeriod = Period::getCurrentPeriod();
    }
    catch(sfException $e)
    {
        return;
    }
    if(false !== $iPeriod)
    {
      $oStatistics->setPeriodId($iPeriod);
      $oStatistics->save();
    }
  }
  
  public function getNameLanguages()
  {
    return $this->getNameEn().' / '.$this->getNameRu();
  }

  public function getNameSlug()
  {
    return SlugifyClass::Slugify($this->getNameEn());
  }

  /**
   * Get query for Category Articles List
   *
   * @param int $u_user_id - U_user ID or 0
   * @return object Doctrine_Query
   */
  public function getCategoryArticlesListQuery($u_user_id = 0)
  {
    $q = ContentTable::getInstance()->addContentPublishedListQuery();
    
    $alias = $q->getRootAlias();
    $q->andWhere($alias.'.id_category=?', $this->getId());
    
    // Filter by U_user purchased content
    if($u_user_id != 0)
    {
      $q->andWhere($alias.'.id NOT IN (SELECT cp.id_content FROM ContentPurchase cp WHERE cp.id_user=?)', $u_user_id);
    }
    $q->orderBy('updated_at DESC');

    return $q;
  }

  /**
   * Get published articles list. Show full atricles list for this category
   *
   * @param int $category_id - Article categoty ID
   * @return object Doctrine_Collection
   */
  public function getCategoryArticlesList()
  {
    $q = $this->getCategoryArticlesListQuery();
    return $q->execute();
  }
}