<?php

/**
 * ContentPurchaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentPurchaseTable extends Doctrine_Table
{
  public function isUserArticle($in)
  {
    $q = Doctrine_Query::create()
          ->select('id_user')
          ->from('ContentPurchase cp')
          ->where('id_user=?', $in['id_user'])
          ->andWhere('id_content=?', $in['id_content'])
          ->limit(1);
    return $q->execute(array(), Doctrine::HYDRATE_SINGLE_SCALAR);
  }

  /**
   * Returns an instance of this class.
   *
   * @return object ContentPurchaseTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('ContentPurchase');
  }

  /**
   * Returns DoctrineCollection of purchases with id_content in $contentIds
   * @param <array> $contentIds
   * @return <DoctrineCollection>
   */
  public function getPurchaseContent($contentIds = array())
  {
    if(!count($contentIds) > 0)
      return false;
    $q = Doctrine_Query::create()
                           ->select('cp.*')
                           ->from('ContentPurchase cp')
                           ->whereIn('cp.id_category',$contentIds);

      return $q->execute();
  }

  public static function getUserPurchaseByCategoryQuery($userId = 0, $categoryId = 0)
  {
    $q = Doctrine_Query::create()
      ->select('cont.*, cat.*, u.*, cp.*')
      ->from('ContentPurchase cp')
      ->innerJoin('cp.Content cont')
      ->innerJoin('cp.Category cat')
      ->innerJoin('cp.User u')
      ->where('cp.id_category=?', $categoryId)
      ->andWhere('cp.id_user=?', $userId);

    return $q;
  }
}