<?php

/**
 * ContentPurchase
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContentPurchase extends BaseContentPurchase
{
    /**
     * User purchase article
     *
     * @param int $user_id
     * @param int $article_id
     * @return bool
     */
    public function userPurchaseArticle($user_id, $article_id, $transaction)
    {
        if (!$article = ContentTable::getInstance()->getArticleForSale($article_id)) {
            return false;
        }

        $this->setIdUser($user_id);
        $this->setIdContent($article_id);
        $this->setIdCategory($article->getIdCategory());
        $this->setTransaction($transaction);
        $this->save();

        return true;
    }

}