<?php

/**
 * ContentRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ContentRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentRating');
    }

    /**
     * Returns Ratings for article by period
     *
     * @param integer $iArticleId
     * @param integer $iPeriodId
     * @return Doctrine_Collection
     */
    public static function getRatesByArticle($iArticleId, $iPeriodId = null)
    {
      $q = Doctrine_Query::create()
        ->select('cr.*')
        ->from('ContentRating cr')
        ->where('cr.content_id=?',$iArticleId);
      if(null !== $iPeriodId)
        $q->andWhere('cr.period_id=?', $iPeriodId);
      
      return $q->execute();
    }
}