<?php

/**
 * Group__PermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Group__PermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Group__PermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Group__Permission');
    }
}