<?php

/**
 * PageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table
{
    const PAGE_CONTACT = 'contact';
    
    public static function getContactPage()
    {
        $page = PageTable::getInstance()->findOneByUrl('contact');
        if(null === $page)
        {
            throw new LogicException(__CLASS__.': Contact page not found');
        }
        return $page;
    }
    
    /**
     * Returns an instance of this class.
     *
     * @return object PageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Page');
    }
}