<?php

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage
{

  /**
   * Returns parent page name
   *
   * @return <string> page name
   */
  public function getParentName()
  {
    return $this->getParent()->getName();
  }
}
