<?php

/**
 * ParagraphTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParagraphTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParagraphTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paragraph');
    }
}