<?php

/**
 * Paragraph
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paragraph extends BaseParagraph
{

    public function getPathPhotoRu()
    {
        return ($this->getPhotoRu() !== null) ? sfConfig::get('app_articles_photo_dir') . '/ru/' . $this->getPhotoRu(
        ) : false;
    }

    public function getPathPhotoEn()
    {
        return ($this->getPhotoEn() !== null) ? sfConfig::get('app_articles_photo_dir') . '/en/' . $this->getPhotoEn(
        ) : false;
    }

    public function getParagraphStyle()
    {
        $out = array();
        if ($this->getIsBold()) {
            $out[] = "bold";
        }
        if ($this->getIsItalic()) {
            $out[] =  "ita";
        }
        if ($this->getHStyle() != 'none') {
            $out[] = "h" . $this->getHStyle();
        } else {
            $out[] = "";
        }

        return join(' ', $out);
    }
}
