<?php

/**
 * PeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return <PeriodTable> object PeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Period');
    }
}