<?php

/**
 * RoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Room');
    }
}