<?php

/**
 * Room
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Room extends BaseRoom
{
  
  public function getFormatedName()
  {
      return str_replace('r', 'R', $this->getName());
  }
  
  /**
   * Returns D0ctrine_Query for current room ordered DESC
   * @return <Doctrine_Query> $q
   */
  public function getTopicOrderByDateQuery()
  {
    $q = Doctrine_Query::create()
      ->from('Topic t')
      ->where('t.id_room = ?', $this->getId())
      ->orderBy('t.created_at DESC');

    return $q;
  }

  /**
   * Returns Topic Collection for current room ordered DESC
   * @return <DoctrineCollection> TopicCollection
   */
  public function getTopicOrderByDate($limit = 10)
  {
    $q = $this->getTopicOrderByDateQuery();
    $q->limit($limit);

    return $q->execute();
  }
}
