<?php

/**
 * SettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SettingTable extends Doctrine_Table
{
  
  public static function getAllTariffs()
  {
    $out[User::STANDART]  = SettingTable::getOptionByName(User::STANDART)->getValue();
    $out[User::EXPERT]    = SettingTable::getOptionByName(User::EXPERT)->getValue();
    $out[User::SUPER]     = SettingTable::getOptionByName(User::SUPER)->getValue();
    return $out;
  }
  
  /**
  * Returns option with $optionName from table Setting
  * @param <string> $optionName
  * @return <object> DoctrineObject
  */
  public static function getOptionByName($optionName)
  {
    $q = Doctrine_Query::create()
      ->select('s.*')
      ->from('Setting s')
      ->where('s.name = ?', $optionName)
      ->limit(1);
    
    return $q->fetchOne();
  }
  
  /**
   * Return Project settings
   *
   * @return Doctrine_collection
   */
  public function getSettings()
  {
//    throw new sfException('!!! Unsuported method: SettingTable::getSettings()');
    return $this->find(1);
  }
  
    /**
     * Returns an instance of this class.
     *
     * @return object SettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Setting');
    }
}