<?php

/**
 * StatisticsCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticsCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticsCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatisticsCategory');
    }
}