<?php

/**
 * Topic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    read2read
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Topic extends BaseTopic
{
  /**
   * Returns room name for topic
   * @return <string> Room name
   */
  public function getRoomName()
  {
    return $this->getRoom()->getName();
  }

  /**
   * 
   * Creates query of posts for current category
   *
   * @return <Doctrine_Query> $q
   */
  public function getTopicPostsQuery()
  {
    $q = Doctrine_Query::create()
      ->from('Post p')
      ->where('p.id_topic = ?', $this->getId())
      ->orderBy('p.created_at ASC');

    return $q;
  }

  /**
   * Returns the posts of the topic with limits
   * @param <integer> $limit
   * @return <DoctrineCollection> posts of the topic
   */
  public function getTopicPosts($limit = 10)
  {
    $q = $this->getTopicPostsQuery()
      ->limit($limit);

    return $q->execute();
  }
}
