<?php

/**
 * User__GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User__GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User__GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User__Group');
    }
}