<?php

/**
 * UserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserPermission');
    }
}