<?php

/**
 * VotersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VotersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VotersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Voters');
    }
}