<?php

/**
 * VoteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote');
    }

    public function getUserVote($userId)
    {
        return self::getInstance()->findByDql(
            'id_period=? AND id_user=?',
            array(Period::getCurrentPeriod()->getId(), $userId)
        );
    }

    public function getUserVotersVote($userId)
    {
        $q = Doctrine_Query::create()
            ->select('v.*, vr.*')
            ->from('Vote v')
            ->innerJoin('v.Voters vr')
            ->where('v.id_period = ?', Period::getCurrentPeriod()->getId())
            ->andWhere('vr.id_user = ?', $userId);

        return $q->fetchOne();
    }

    public static function setPositions()
    {
        $q = Doctrine_Query::create()
            ->select('v.*')
            ->from('Vote v')
            ->where('v.id_period = ?', Period::getCurrentPeriod()->getId())
            ->orderBy('v.weight DESC');

        $votes = $q->execute();

        $k = 1;
        foreach ($votes as $i => $vote) {
            $k += $i;
            $vote->setPosition($k);
            $vote->save();
        }
    }

    public static function getVoted1k(Period $period)
    {
        $q = Doctrine_Query::create()
            ->select('v.*')
            ->from('Vote v')
            ->where('v.id_period = ?', $period->getId())
            ->andWhere('v.weight > 50')
            ->execute()->getFirst();

        if ($q) {
            return $q->getPrice();
        } else {
            return false;
        }
    }

    public static function getVotesList($periodId)
    {
        $q = Doctrine_Query::create()
            ->select('v.*')
            ->from('Vote v')
            ->where('v.id_period = ?', $periodId)
            ->orderBy('v.position ASC');

        return $q->execute();
    }
}