<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'page_description', 'string', '', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'page_description');
    }
}