<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('setting', 'value', 'string', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('setting', 'value', 'string', '255', array(
            'notnull' => '1',
        ));
    }
}