<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('user');
        $this->addColumn('user', 'weight', 'decimal', '18', array(
             'scale' => '2',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'login' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '100',
             ),
             'email' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '80',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '80',
             ),
             'live_place' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'site' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'account_number' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '20',
             ),
             'skype' => 
             array(
              'type' => 'string',
              'length' => '40',
             ),
             'resume_text' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'avatar' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'userpic' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'const_msg' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'activation_code' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '50',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'utype' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'puser',
              1 => 'uuser',
              2 => 'suser',
              ),
              'default' => 'uuser',
              'length' => '',
             ),
             'is_blocked' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'tariff' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'none',
              1 => 'standart',
              2 => 'expert',
              3 => 'super',
              ),
              'default' => 'none',
              'length' => '',
             ),
             'tariff_change' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'none',
              1 => 'standart',
              2 => 'expert',
              3 => 'super',
              ),
              'default' => 'none',
              'length' => '',
             ),
             'tariff_change_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'balans' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'notnull' => '1',
              'length' => '18',
             ),
             'last_login' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             'last_purchase' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             'sells' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'img_file_size' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'img_file_md5' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'img_file_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
              'user_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('user', 'weight');
    }
}