<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'weight', 'decimal', '18', array(
             'scale' => '2',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'weight');
    }
}