<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'contact_email', 'string', '80', array(
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'contact_email');
    }
}