<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('content', 'is_bold', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('content', 'is_italic', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('content', 'h_style', 'enum', '', array(
             'values' => 
             array(
              0 => 'none',
              1 => '1',
              2 => '2',
              3 => '3',
              4 => '4',
              5 => '5',
              6 => '6',
             ),
             'default' => 'none',
             ));
        $this->addColumn('paragraph', 'is_bold', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('paragraph', 'is_italic', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('paragraph', 'h_style', 'enum', '', array(
             'values' => 
             array(
              0 => 'none',
              1 => '4',
              2 => '5',
              3 => '6',
             ),
             'default' => 'none',
             ));
        $this->addColumn('paragraph', 'pad_left', 'integer', '2', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('content', 'is_bold');
        $this->removeColumn('content', 'is_italic');
        $this->removeColumn('content', 'h_style');
        $this->removeColumn('paragraph', 'is_bold');
        $this->removeColumn('paragraph', 'is_italic');
        $this->removeColumn('paragraph', 'h_style');
        $this->removeColumn('paragraph', 'pad_left');
    }
}