<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('paragraph', 'is_photo', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('paragraph', 'photo_ru', 'string', '200', array(
             ));
        $this->addColumn('paragraph', 'photo_en', 'string', '200', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('paragraph', 'is_photo');
        $this->removeColumn('paragraph', 'photo_ru');
        $this->removeColumn('paragraph', 'photo_en');
    }
}