<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('content_purchase', 'id_transaction', 'integer', '8', array(
             ));

        $this->createForeignKey('content_purchase', 'content_purchase_id_transaction_transaction_id', array(
                'name' => 'content_purchase_id_transaction_transaction_id',
                'local' => 'id_transaction',
                'foreign' => 'id',
                'foreignTable' => 'transaction',
            ));
        $this->addIndex('content_purchase', 'content_purchase_id_transaction', array(
                'fields' =>
                array(
                    0 => 'id_transaction',
                ),
            ));

    }

    public function down()
    {
        $this->dropForeignKey('content_purchase', 'content_purchase_id_transaction_transaction_id');
        $this->removeIndex('content_purchase', 'content_purchase_id_transaction', array(
                'fields' =>
                array(
                    0 => 'id_transaction',
                ),
            ));

        $this->removeColumn('content_purchase', 'id_transaction');
    }
}