<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('paragraph', 'paragraph_id_content_content_id');
        $this->createForeignKey('paragraph', 'paragraph_id_content_content_id', array(
             'name' => 'paragraph_id_content_content_id',
             'local' => 'id_content',
             'foreign' => 'id',
             'foreignTable' => 'content',
             'onUpdate' => '',
             'onDelete' => 'Cascade',
             ));
        $this->addIndex('paragraph', 'paragraph_id_content', array(
             'fields' => 
             array(
              0 => 'id_content',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('paragraph', 'paragraph_id_content_content_id');
        $this->createForeignKey('paragraph', 'paragraph_id_content_content_id', array(
             'name' => 'paragraph_id_content_content_id',
             'local' => 'id_content',
             'foreign' => 'id',
             'foreignTable' => 'content',
             ));
        $this->removeIndex('paragraph', 'paragraph_id_content', array(
             'fields' => 
             array(
              0 => 'id_content',
             ),
             ));
    }
}