<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('content', 'content_id_user_user_id');
        $this->dropForeignKey('content_purchase', 'content_purchase_id_content_content_id');
        $this->createForeignKey('content', 'content_id_user_user_id', array(
             'name' => 'content_id_user_user_id',
             'local' => 'id_user',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'Cascade',
             ));
        $this->createForeignKey('content_purchase', 'content_purchase_id_content_content_id', array(
             'name' => 'content_purchase_id_content_content_id',
             'local' => 'id_content',
             'foreign' => 'id',
             'foreignTable' => 'content',
             'onUpdate' => '',
             'onDelete' => 'Cascade',
             ));
        $this->addIndex('content', 'content_id_user', array(
             'fields' => 
             array(
              0 => 'id_user',
             ),
             ));
        $this->addIndex('content_purchase', 'content_purchase_id_content', array(
             'fields' => 
             array(
              0 => 'id_content',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('content', 'content_id_user_user_id');
        $this->dropForeignKey('content_purchase', 'content_purchase_id_content_content_id');
        $this->createForeignKey('content', 'content_id_user_user_id', array(
             'name' => 'content_id_user_user_id',
             'local' => 'id_user',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('content_purchase', 'content_purchase_id_content_content_id', array(
             'name' => 'content_purchase_id_content_content_id',
             'local' => 'id_content',
             'foreign' => 'id',
             'foreignTable' => 'content',
             ));
        $this->removeIndex('content', 'content_id_user', array(
             'fields' => 
             array(
              0 => 'id_user',
             ),
             ));
        $this->removeIndex('content_purchase', 'content_purchase_id_content', array(
             'fields' => 
             array(
              0 => 'id_content',
             ),
             ));
    }
}