<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('comment', 'comment_id_paragraph_paragraph_id');
        $this->createForeignKey('comment', 'comment_id_paragraph_paragraph_id', array(
             'name' => 'comment_id_paragraph_paragraph_id',
             'local' => 'id_paragraph',
             'foreign' => 'id',
             'foreignTable' => 'paragraph',
             'onUpdate' => '',
             'onDelete' => 'Cascade',
             ));
        $this->addIndex('comment', 'comment_id_paragraph', array(
             'fields' => 
             array(
              0 => 'id_paragraph',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_id_paragraph_paragraph_id');
        $this->createForeignKey('comment', 'comment_id_paragraph_paragraph_id', array(
             'name' => 'comment_id_paragraph_paragraph_id',
             'local' => 'id_paragraph',
             'foreign' => 'id',
             'foreignTable' => 'paragraph',
             ));
        $this->removeIndex('comment', 'comment_id_paragraph', array(
             'fields' => 
             array(
              0 => 'id_paragraph',
             ),
             ));
    }
}