<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('period', 'r2r_share', 'decimal', '18', array(
             'scale' => '2',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('period', 'r2r_share');
    }
}