<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/03 15:56:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=db_nosort_1',
  'username' => 'dbu_nosort_1',
  'password' => 'NyJEU5Ivsm1',
  'name' => 'doctrine',
)),);
